# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Use Scroll Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
    
